### ISSUE TITLE
alicloud not updated to support python 3.7

### ISSUE THREAD

**Issue by yannrouillard** [pulumi/pulumi-alicloud#1]
According to https://pulumi.io/reference/python.html, last versions of pulumi only support python 3.7 but it seems this module still only works with python 2.7.

I currently get the following errors when importing the module in pulumi project:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yann/.local/share/virtualenvs/testalibaba-iJ75DxjS/lib/python3.7/site-packages/pulumi_alicloud/__init__.py", line 9, in <module>
    from get_account import *
ModuleNotFoundError: No module named 'get_account'
```

Which is caused by using the line `from get_account import *`instead of `from .get_account import *` in `pulumi_alicloud/__init__.py`.

Solving this issue further leads to the error:
```
  File "[..]/lib/python3.7/site-packages/pulumi_alicloud/ecs/instance.py", line 28, in __init__
        if not isinstance(__name__, basestring):
    NameError: name 'basestring' is not defined
```

So it seems to be a python 2 / python 3 issue.

Can you confirm the issue and is pulumi-alicloud still supported for newest versions ?

Thanks in advance for your work.

**Comment by stack72** [comment]
I believe that #5 will take care of this - it was an abandoned provider until this week but it's back to the same standard as that of the rest of the providers
