### ISSUE TITLE
error: Invalid type option, support

### ISSUE THREAD

**Issue by Mr-YYM** [pulumi/pulumi-alicloud#187]
## Steps to reproduce

my `__main__.py`

```python
"""A Python Pulumi program"""

import pulumi
from pulumi_alicloud.vpc import Network

vpc = Network("my-vpc",
    cidr_block="192.168.0.0/16"
)
```

I set the env:

```shell
export ALICLOUD_ACCESS_KEY=[]
export ALICLOUD_ACCESS_SECRET=[]
export ALICLOUD_REGION=cn-shenzhen
```

after that, an error occur: 

```shell
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
Previewing update (dev):
     Type                     Name             Plan       Info
 +   pulumi:pulumi:Stack      pulumi_demo-dev  create     
     └─ alicloud:vpc:Network  my-vpc                      1 error

Diagnostics:
  alicloud:vpc:Network (my-vpc):
    error: Invalid type option, support: access_key, sts, ecs_ram_role, ram_role_arn, rsa_key_pair
 ```

my package version:

```shell
➜  pulumi_demo# pip3 freeze|grep pulumi
pulumi==3.6.1
pulumi-alicloud==3.2.0

➜  pulumi_demo# pulumi version
v3.6.1
```

**Comment by lukehoban** [comment]
Just to make sure  - is it possible you have additional environment variables specified?  In particular `ALIBABA_CLOUD_CREDENTIALS_FILE` or something else which might cause the Alicloud SDK to try to look somewhere other than the env vars you listed above?

As you shared above - this should work as you expect - so my best guess is there is some other configuration on your system which is interfering.

**Comment by Mr-YYM** [comment]
@lukehoban I can confirm that there is no other configuration, there is no other env

I change the config file `Pulumi.dev.yaml` like this, it work

```yaml
encryptionsalt: v1:.......==
config:
  alicloud:accessKey: ""
  alicloud:secretKey: ""
  alicloud:region: "cn-shenzhen"
```

**Comment by lukehoban** [comment]
>  `export ALICLOUD_ACCESS_SECRET=[]`

Looks like the name of this env var is incorrect, it should be `ALICLOUD_SECRET_KEY` per https://www.pulumi.com/docs/intro/cloud-providers/alicloud/setup/.

**Comment by Mr-YYM** [comment]
same problem when `ALICLOUD_SECRET_KEY` is set
