### ISSUE TITLE
Bad API docs link in README.md

### ISSUE THREAD

**Issue by t12g** [pulumi/pulumi-alicloud#2]
The API docs [link](https://pulumi.io/reference/pkg/nodejs/@pulumi/alicloud/index.html) under the [reference section](https://github.com/pulumi/pulumi-alicloud#reference) points to a non-existent page.

**Comment by stack72** [comment]
This will be taken care of by this round of work to publish the provider - PR is open for the update in #5 and will go to the site shortly after that
