### ISSUE TITLE
Does DomainNew support configure URL redirection?

### ISSUE THREAD

**Issue by anhnguyenkim-agilityio** [pulumi/pulumi-alicloud#235]
Does have any way to configure URL redirection for CDN like that https://www.alibabacloud.com/help/en/doc-detail/27133.htm?

**Note**
- I'm using pulumi-alicloud version: v2.31.0

**Comment by iwahbe** [comment]
I'm not sure. This provider is generated from https://github.com/aliyun/terraform-provider-alicloud. I'm not an expert on alicloud. 

I'd recommend opening a similar issue upstream, which is maintained by alicloud. If there is a way to do so in the alicloud's TF provider, I can show you how to do it in this Pulumi provider.
