### ISSUE TITLE
latest version can't be used

### ISSUE THREAD

**Issue by kordenlu** [pulumi/pulumi-alicloud#260]
## Issue details

go get latest version failed

### Steps to reproduce

1. go get github.com/pulumi/pulumi-alicloud/sdk/v3@latest

Expected: go get success
Actual: `go: github.com/pulumi/pulumi-alicloud/sdk/v3@v3.18.0: reading github.com/pulumi/pulumi-alicloud/sdk/sdk/go.mod at revision sdk/v3.18.0: unknown revision sdk/v3.18.0
`

### Possible cause

<img width="395" alt="image" src="https://user-images.githubusercontent.com/5573997/158209210-b0aace03-2eb0-4a42-9385-981cc23aa5b3.png">

**Comment by jkodroff** [comment]
@kordenlu Thanks for reporting this. The issue was due to a bug in our GH actions. The fix has been merged here: https://github.com/pulumi/pulumi-alicloud/pull/257

I've also fixed the tags on 3.17.0 and 3.18.0.
