### ISSUE TITLE
PolicyName is required

### ISSUE THREAD

**Issue by bingtsingw** [pulumi/pulumi-alicloud#271]
### What happened?

throw error on creating resource

### Steps to reproduce

```
new alicloud.ram.Policy(name, {
      policyDocument: 'xxx',
    });
```

### Expected Behavior

create a policy with auto-naming

### Actual Behavior

```
    error: [ERROR] terraform-provider-alicloud@v1.160.0/alicloud/resource_alicloud_ram_policy.go:191: Resource alicloud_ram_policy CreatePolicy Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
    SDKError:
       StatusCode: 400
       Code: MissingParameter
       Message: code: 400, Parameter PolicyName is required. request id: 3FA8B83F-902F-5C59-83B6-E5524648EC58
       Data: {"Code":"MissingParameter","HostId":"ram.aliyuncs.com","Message":"Parameter PolicyName is required.","Recommend":"https://troubleshoot.api.aliyun.com?q=MissingParameter\u0026product=Ram","RequestId":"3FA8B83F-902F-5C59-83B6-E5524648EC58"}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for filing this issue. It does appear that [policyName is required upstream](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/ram_policy#policy_name) but our docs should reflect this.

**Comment by guineveresaenger** [comment]
update: I dug around some more, and this is an upstream issue - the Terraform resource [lists this field as optional](https://github.com/aliyun/terraform-provider-alicloud/blob/master/alicloud/resource_alicloud_ram_policy.go#L63) (their docs do not) and you're seeing the error from Alicloud.

**Comment by bingtsingw** [comment]
> update: I dug around some more, and this is an upstream issue - the Terraform resource [lists this field as optional](https://github.com/aliyun/terraform-provider-alicloud/blob/master/alicloud/resource_alicloud_ram_policy.go#L63) (their docs do not) and you're seeing the error from Alicloud.

Should we fix it in pulumi side by remove this field, or we need to wait the upstream repo to fix it first
