### ISSUE TITLE
support Java

### ISSUE THREAD

**Issue by daleiz** [pulumi/pulumi-alicloud#279]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add Java support

**Comment by stack72** [comment]
Hi @daleiz 

We actually do have Java support for this provider :) https://mvnrepository.com/artifact/com.pulumi/oci

Please let us know if this isn't working and we can investigate it

Paul
