### ISSUE TITLE
Use pulumi config to configure accessKey, secretKey doesn't work

### ISSUE THREAD

**Issue by daanporon** [pulumi/pulumi-alicloud#326]
### What happened?

When i configure my credentials using pulumi config, i'm always getting the following issue:

`Invalid type option, support: access_key, sts, ecs_ram_role, ram_role_arn, rsa_key_pair`

I have the feeling that the configuration variables aren't given to the alicloud-terraform provider. The only way to make it work is by setting the environment variables, which will then be picked up directly by the terraform provider.

### Steps to reproduce

Use 

```
pulumi config set alicloud:accessKey YOUR_ACCESS_KEY  --secret
pulumi config set alicloud:secretKey YOUR_SECRET  --secret
```

To configure pulumi-alicloud in stead of the 

```
export ALICLOUD_ACCESS_KEY=YOUR_ACCESS_KEY
export ALICLOUD_SECRET_KEY=YOUR_SECRET
```

environment variables

### Expected Behavior

It should be able to connect

### Actual Behavior

I'm getting this error

`Invalid type option, support: access_key, sts, ecs_ram_role, ram_role_arn, rsa_key_pair`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by daanporon** [comment]
It's related to this one i think: https://github.com/pulumi/pulumi-alicloud/issues/187 but it was closed.

**Comment by guineveresaenger** [comment]
hi @daanporon - can you try the following:
`pulumi config set alicloud:access_key YOUR_ACCESS_KEY  --secret` ?

**Comment by guineveresaenger** [comment]
Hi @daanporon -

I just tried to set my configuration, and we apologize. This is an error in our configuration&installation documentation.

You should be fine if you run

`pulumi config set alicloud:access_key YOUR_ACCESS_KEY --secret`
`pulumi config set alicloud:secret_key YOUR_SECRET_KEY --secret`

I will fix the documentation.

**Comment by guineveresaenger** [comment]
Update:

I tried this with both `access_key` and `accessKey` and I could not reproduce the issue.

Can you confirm you are using the latest version of Pulumi?

**Comment by daanporon** [comment]
hi, @guineveresaenger,

i just updated Pulumi to version v3.48.0 and i'm still having the same issue. I am using pulumi/alicloud version v3.28.0.

I also tried it with updating the config to what you proposed:

`config:
  alicloud:access_key:
    secure: THE_KEY
  alicloud:region: eu-central-1
  alicloud:secret_key:
    secure: THE_SECRET
`
And i'm still having the issue.

**Comment by daanporon** [comment]
nvm, i found the issue .. it was my bad .
I override the provider and i think that's why the config was gone 🥲, i thought it would enrich the existing provider.
