### ISSUE TITLE
please add docs for alicloud.vpc.RouteEntry inputs NexthopType Available values

### ISSUE THREAD

**Issue by williamwangis** [pulumi/pulumi-alicloud#349]
Need to add docs for alicloud.vpc.RouteEntry inputs NexthopType Available values

**Comment by iwahbe** [comment]
![Image](https://github.com/user-attachments/assets/01d9a1c0-7a50-4be3-9650-0a056518f5f5)

We have added available values to https://www.pulumi.com/registry/packages/alicloud/api-docs/vpc/routeentry/.
