### ISSUE TITLE
ALB create with error: attribute supports 2 item as a minimum

### ISSUE THREAD

**Issue by twasa** [pulumi/pulumi-alicloud#379]
### What happened?

Pulumi runtime: Python
reference to https://www.pulumi.com/registry/packages/alicloud/api-docs/alb/loadbalancer/

Create a ALB and got error if zone_mappings only config with one item

pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:prod::v16team::pulumi:pulumi:Stack::my-prod]
error: alicloud:alb/loadBalancer:LoadBalancer resource 'my-alb' has a problem: zone_mappings: attribute supports 2 item as a minimum, config has 1 declared

### Expected Behavior

Aliyun in region philippine(Manila) has only single AZ, it is impossible to create 2 items

### Steps to reproduce

none

### Output of `pulumi about`
CLI
Version      3.60.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
alicloud    3.33.0
aws         5.21.1
kubernetes  3.23.1
python      3.11.2

Host
OS       darwin
Version  13.2.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @twasa - I'm not sure you need to set the zone mappings at all if there is only one zone.

Can you see what happens if you leave out that field?

If you're still having trouble, can you send us a minimum reproduction that we can run on our end to further investigate?

**Comment by williamwangis** [comment]
TypeError: Missing required property 'zone_mappings'

**Comment by twasa** [comment]
try and find the tricky solution, just specific duplicate vswitch_id and zone_id

zone_mappings = [
    alb.LoadBalancerZoneMappingArgs(
        vswitch_id=vswitch1.id,
        zone_id=vswitch1.zone_id
    ),
    alb.LoadBalancerZoneMappingArgs(
        vswitch_id=vswitch1.id,
        zone_id=vswitch1.zone_id
    ),
]

**Comment by mjeffryes** [comment]
It looks like this problem was solved.
