### ISSUE TITLE
missing kubernetes NodePool attribute `eip_internet_charge_type`

### ISSUE THREAD

**Issue by nicolasochem** [pulumi/pulumi-alicloud#429]
### What happened?

I'm trying to deploy a AKS cluster where nodes are directly connected to the internet (no VPC) in order to avoid NAT gateway charges.

### Expected Behavior

I expect to be able to set `eip_internet_charge_type`

From [terraform doc](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_kubernetes_node_pool):

```
[eip_internet_charge_type](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/cs_kubernetes_node_pool#eip_internet_charge_type) - (Optional, Available in 1.111.0+) EIP billing type. PayByBandwidth: Charged at fixed bandwidth. PayByTraffic: Billed as used traffic. Default: PayByBandwidth. Conflict with internet_charge_type, EIP and public network IP can only choose one.
```

But I do not see this attribute set anywhere in the typescript source code:

https://github.com/pulumi/pulumi-alicloud/blob/master/sdk/nodejs/cs/nodePool.ts#L413-L416

### Steps to reproduce

I don't see the attribute.

### Output of `pulumi about`

```

CLI          
Version      3.69.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       fedora
Version  37
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Looking at the terraform docs, `eip_internet_charge_type` is mentioned on the doc for `internet_charge_type`, but is not actually present on the top level resource. It is instead present on the `scaling_config` object.

Pulumi has the same structure. 

scalingConfig:

https://github.com/pulumi/pulumi-alicloud/blob/f6018913a9484b845fcbccf07cc86213464accf9/sdk/nodejs/cs/nodePool.ts#L1162-L1166

eipInternetChargeType:

https://github.com/pulumi/pulumi-alicloud/blob/f6018913a9484b845fcbccf07cc86213464accf9/sdk/nodejs/types/input.ts#L2887-L2890

You can set `eipInternetChargeType` by passing `scalingConfig: { eipInternetChangeType: yourValue }`.
