### ISSUE TITLE
The input: nexthop_type value "IPv4Gateway" does not work.

### ISSUE THREAD

**Issue by ponlayookm** [pulumi/pulumi-alicloud#736]
File: [themes/default/content/registry/packages/alicloud/api-docs/vpc/routeentry/_index.md](https://www.pulumi.com/registry/packages/alicloud/api-docs/vpc/routeentry/)

Alibaba's API doc hasn't updated yet : https://api.alibabacloud.com/document/Vpc/2016-04-28/CreateRouteEntry?spm=api-workbench-intl.Product%20Home%20Page.0.0.5c594f450DeOKi

The GUI has IPV4 Gateway available to select.
Terraform registry has it but with small "p" not capital "P" (Didn't test if it works)
https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/route_entry

This affect Pulumi CLI as well.

PS. I'm not an experienced coder, so if I've made mistakes please kindly point out my error.

**Comment by iwahbe** [comment]
Hi @ponlayookm. If you are still experiencing this issue, please open a new issue explaining what you were trying to do and what actually happened. Please include a code sample in the new issue along with the output of running `pulumi up` or `pulumi import`.
