### ISSUE TITLE
Does pulumi serverless functionality available for Alibaba Cloud?

### ISSUE THREAD

**Issue by hryang** [pulumi/pulumi-alicloud#87]
In https://www.pulumi.com/serverless/, pulumi shows the super powers for serverless application on AWS platform. Does these functionalities are available for Alibaba Cloud? If not, any plan to support it?

**Comment by leezen** [comment]
You can still use the closure capabilities, but it's not wrapped as conveniently. You'll want to take a look at `pulumi.runtime.serializeFunction`. https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/lambda/lambdaMixins.ts#L304 might provide a helpful reference for how to construct the serialized function.
